### ISSUE TITLE
ESP8266 MemoryError

### ISSUE THREAD

**Issue by nevalain** [rdehuyss/micropython-ota-updater#1]
It seems that with ESP8266 this can be used to OTA update only quite small files. I tried this with small files that worked well but a file with ~5000 bytes throw an error:
MemoryError: memory allocation failed, allocating 6656 bytes

Maybe there could be a way to bypass this problem?

(I needed to put this in esp8266/modules to run this without memoryerror. That could be added as a tip in readme.)

Thanks for a nice tool!

**Comment by rdehuyss** [comment]
Hi @nevalain ,

Thanks for your feedback - I also had some issues with file sizes, don't remember exactly how I solved them.

You mention putting something in a modules folder: how does this help? Aren't we just reaching the memory limits from the various esp* devices? 

Curious on your feedback...

Cheers,
Ronald

**Comment by nevalain** [comment]
I think that the memory error happens in row 137:
` response = self.http_client.get(url)
`
The command tries to read file to memory before writing it to the flash and fails because it is out of memory?

Workaround is of course to use smaller files, but that may be time consuming. Forgive me that I am not expert in coding.

(I ment that with ESP8266 I needed to put the micropython-ota-updater (ota_updater.py) to freeze it: https://learn.adafruit.com/micropython-basics-loading-modules/frozen-modules)

**Comment by EmilySieben** [comment]
> The command tries to read file to memory before writing it to the flash and fails because it is out of memory?

Yes, that's the reason. The actual problem is in line 165 of ota_updater.py:

`self._cached = self.raw.read()`

...this call reads the whole HTTP response **at once**. You could read the data in chunks instead, but the file object is not available in that context.

Example:

```python
CHUNK_SIZE = 1024 # bytes
output_file = open('outfile', 'wb+')
data = sc.recv(CHUNK_SIZE)
while data:
    output_file.write(data)
    data = sc.recv(CHUNK_SIZE)
```

That way you allocate only 1024 bytes at once, and immediately append them to the file.

**Comment by rdehuyss** [comment]
@timeless-engine - are you willing to create a PR which fixes the problem?

Thanks in advance,
Ronald

**Comment by rdehuyss** [comment]
Memory issues are solved - still struggling with ssl however
