### ISSUE TITLE
Not detecting 'New Version' - How to declare a 'new version' ?

### ISSUE THREAD

**Issue by FalconBFR** [rdehuyss/micropython-ota-updater#10]
Dear @rdehuyss,

Sorry for bothering you again. I managed to integrate your library / code into my current project but I am struggling to get it to recognise a 'new version'. I also tried looking at other past issues but I haven't found anything about it. How do I define a new version? Do I create a new release or does it just auto detect? Thank you very much for creating and open sourcing such a helpful project and for your kind help in advance!

Clement

Context:
My repo is a private repo and all my code, including main.py and ota_updater.py is in the folder 'main'. My check fr OTA function runs every time it is booted in boot.py:
```print("OTA Check for new version")
def ota_update_checker():
    #from ota_updater.main.ota_updater import OTAUpdater
    from ota_updater import OTAUpdater
    token='CENSORED TOKEN'
    updater = OTAUpdater('CENSOREDREPOLINK', headers={'Authorization': 'token {}'.format(token)})
    wifi_details = ""
    wifi_ssid = ""
    wifi_password = ""
    try:
        wifi_details = open('wifi.dat').read()
        wifi_details.split(';')
        wifi_ssid = wifi_details[0]
        wifi_password = wifi_details[1][:-2]
        print(wifi_ssid)
        print(wifi_password)
    except:
        print("No wifi detials - not set up yet - first time user? Skip!")
        return None
    updater.download_and_install_update_if_available(wifi_ssid,wifi_password)
    print("OMG this is a success!")

ota_update_checker()```

**Comment by rdehuyss** [comment]
Just create a new release in your GitHub repo.

If you configured everything correctly, it will auto detect and download the new version.

**Comment by FalconBFR** [comment]
Wow thanks for the quick response. I already created a release but it still isn't working. I went through the code. Just curious, does a new release need to have an integer version number or does GitHub have its internal pk? My version numbers are like v0.910. However, it seems like the same applies to your shower project? Thanks for your help in advance!

**Comment by FalconBFR** [comment]
Note: It prints out an 
'E'
then a blank line before a 'No new updates found...' message

I am unable to locate where this 'E' is coming from. Does it represent an error? Thanks very much!

**Comment by FalconBFR** [comment]
> Just create a new release in your GitHub repo.
> 
> If you configured everything correctly, it will auto detect and download the new version.

Is there anything that I should be aware of? Like token settings (I enabled all of them for now)? Thank you very much!

**Comment by BorysekOndrej** [comment]
Hi, I've also encountered this behaviour today. Looking in the code I've noticed a few things:

If you take the snippet from readme, it will just print out `No new updates found...`.  The thing is, the snippet is missing an important line `o.check_for_update_to_install_during_next_reboot()`. The line is just mentioned in the text.

Now, if you call `o.check_for_update_to_install_during_next_reboot()` without existing `main` folder, the script will crash.
```
  File "ota_update/main/ota_updater.py", line 106, in get_version
OSError: [Errno 2] ENOENT
```
Just create empty folder `main`, that will solve it.

At this point, I started getting 

```
  File "main/ota_updater.py", line 116, in get_latest_version
KeyError: tag_name
```

As mentioned in #9, this is a most often token scope issue, but also could be typo in the repo name. I've confirmed that by looking directly at the response. Sadly, the author of the issue just said that he solved it, not how. I've tried a few combination of repo token scopes and the only one that seems to work for me is main repo one "Full control of private repositories". This made the detection of the new version work, however there was another issue.

```
Traceback (most recent call last):
  File "main.py", line 37, in <module>
  File "main.py", line 32, in boot
  File "main.py", line 12, in download_and_install_update_if_available
  File "ota_update/main/ota_updater.py", line 49, in download_and_install_update_if_available
  File "ota_update/main/ota_updater.py", line 56, in _download_and_install_update
  File "ota_update/main/ota_updater.py", line 126, in download_all_files
TypeError: string indices must be integers, not str
```
```
{'message': 'Not Found', 'documentation_url': 'https://docs.github.com/rest/reference/repos#get-repository-content'}
```
This turned out to be quite simple - even the repository has to has `main` folder. It's name can be changed (passed as argument to `OTAUpdater` class), but if you are fine with creating folder `main` in your repository and making sure that it gets commited (empty folders don't get added, so create .gitkeep file in it), than that will solve it.

If the author doesn't mind, I would love to create PR with some error messages and a few hints in the readme.

**Comment by FalconBFR** [comment]
> Hi, I've also encountered this behaviour today. Looking in the code I've noticed a few things:
> 
> If you take the snippet from readme, it will just print out `No new updates found...`. The thing is, the snippet is missing an important line `o.check_for_update_to_install_during_next_reboot()`. The line is just mentioned in the text.
> 
> Now, if you call `o.check_for_update_to_install_during_next_reboot()` without existing `main` folder, the script will crash.
> 
> ```
>   File "ota_update/main/ota_updater.py", line 106, in get_version
> OSError: [Errno 2] ENOENT
> ```
> 
> Just create empty folder `main`, that will solve it.
> 
> At this point, I started getting
> 
> ```
>   File "main/ota_updater.py", line 116, in get_latest_version
> KeyError: tag_name
> ```
> 
> As mentioned in #9, this is a most often token scope issue, but also could be typo in the repo name. I've confirmed that by looking directly at the response. Sadly, the author of the issue just said that he solved it, not how. I've tried a few combination of repo token scopes and the only one that seems to work for me is main repo one "Full control of private repositories". This made the detection of the new version work, however there was another issue.
> 
> ```
> Traceback (most recent call last):
>   File "main.py", line 37, in <module>
>   File "main.py", line 32, in boot
>   File "main.py", line 12, in download_and_install_update_if_available
>   File "ota_update/main/ota_updater.py", line 49, in download_and_install_update_if_available
>   File "ota_update/main/ota_updater.py", line 56, in _download_and_install_update
>   File "ota_update/main/ota_updater.py", line 126, in download_all_files
> TypeError: string indices must be integers, not str
> ```
> 
> ```
> {'message': 'Not Found', 'documentation_url': 'https://docs.github.com/rest/reference/repos#get-repository-content'}
> ```
> 
> This turned out to be quite simple - even the repository has to has `main` folder. It's name can be changed (passed as argument to `OTAUpdater` class), but if you are fine with creating folder `main` in your repository and making sure that it gets commited (empty folders don't get added, so create .gitkeep file in it), than that will solve it.
> 
> If the author doesn't mind, I would love to create PR with some error messages and a few hints in the readme.

Just to clarify, I haven't solved it yet and I would be grateful if anyone could help me out. Thank you very much.

**Comment by FalconBFR** [comment]
@BorysekOndrej @rdehuyss I allowed everything for my token but it is still not working. Wandering why that is the case. Thanks in advance.

**Comment by FalconBFR** [comment]
Additional Question: Is it okay to have main.py and boot.py inside the main folder or should I have a static and non-updatable main and boot .py that points to main and boot functions located inside the main folder? 

Note: I still can't get it to detect my new releases: Here are a few screenshots of my repo: 

<img width="1560" alt="Screenshot 2020-12-23 at 11 49 50 AM" src="https://user-images.githubusercontent.com/47275378/102957559-a6ccc700-4515-11eb-8e35-b35be0604d29.png">
<img width="1825" alt="Screenshot 2020-12-23 at 11 50 02 AM" src="https://user-images.githubusercontent.com/47275378/102957565-aaf8e480-4515-11eb-8593-0406ee411467.png">


Hopefully these images will provide additional context. Thank you for anyone's help in advance.

**Comment by FalconBFR** [comment]
> Hi, I've also encountered this behaviour today. Looking in the code I've noticed a few things:
> 
> If you take the snippet from readme, it will just print out `No new updates found...`. The thing is, the snippet is missing an important line `o.check_for_update_to_install_during_next_reboot()`. The line is just mentioned in the text.
> 
> Now, if you call `o.check_for_update_to_install_during_next_reboot()` without existing `main` folder, the script will crash.
> 
> ```
>   File "ota_update/main/ota_updater.py", line 106, in get_version
> OSError: [Errno 2] ENOENT
> ```
> 
> Just create empty folder `main`, that will solve it.
> 
> At this point, I started getting
> 
> ```
>   File "main/ota_updater.py", line 116, in get_latest_version
> KeyError: tag_name
> ```
> 
> As mentioned in #9, this is a most often token scope issue, but also could be typo in the repo name. I've confirmed that by looking directly at the response. Sadly, the author of the issue just said that he solved it, not how. I've tried a few combination of repo token scopes and the only one that seems to work for me is main repo one "Full control of private repositories". This made the detection of the new version work, however there was another issue.
> 
> ```
> Traceback (most recent call last):
>   File "main.py", line 37, in <module>
>   File "main.py", line 32, in boot
>   File "main.py", line 12, in download_and_install_update_if_available
>   File "ota_update/main/ota_updater.py", line 49, in download_and_install_update_if_available
>   File "ota_update/main/ota_updater.py", line 56, in _download_and_install_update
>   File "ota_update/main/ota_updater.py", line 126, in download_all_files
> TypeError: string indices must be integers, not str
> ```
> 
> ```
> {'message': 'Not Found', 'documentation_url': 'https://docs.github.com/rest/reference/repos#get-repository-content'}
> ```
> 
> This turned out to be quite simple - even the repository has to has `main` folder. It's name can be changed (passed as argument to `OTAUpdater` class), but if you are fine with creating folder `main` in your repository and making sure that it gets commited (empty folders don't get added, so create .gitkeep file in it), than that will solve it.
> 
> If the author doesn't mind, I would love to create PR with some error messages and a few hints in the readme.

Thanks so much for the advice! After adding the line you suggested, I am stuck with an OS Error 202:
```Traceback (most recent call last):
  File "boot.py", line 30, in <module>
  File "boot.py", line 26, in ota_update_checker
  File "ota_updater.py", line 32, in check_for_update_to_install_during_next_reboot
  File "ota_updater.py", line 114, in get_latest_version
  File "ota_updater.py", line 268, in get
  File "ota_updater.py", line 207, in request
OSError: -202
```

Line 207 is: 
```
ai = usocket.getaddrinfo(host, port, 0, usocket.SOCK_STREAM)
```

Still trying to troubleshoot. Any help will be really appreciated.

**Comment by suysh** [comment]
In the same function `request` I'm also having an` OSError: -40` (see my issue on this repo).
Don't know if this is related.

**Comment by FalconBFR** [comment]
> In the same function `request` I'm also having an` OSError: -40` (see my issue on this repo).
> Don't know if this is related.

Thanks! I will have a look now!

**Comment by rdehuyss** [comment]
Hi guys,

I just updated the OTAUpdater to the latest version which I developed over the last months. Can you try that and start a new issue if stuff does not work?

I used it yesterday and it works nicely for me. It is used in the following project: [https://github.com/rdehuyss/chicken-shed-mgr/tree/main/src/app/utils](https://github.com/rdehuyss/chicken-shed-mgr/tree/main/src/app/utils).

> Do note that there I split the httpclient as it is also used to do logging to GitHub gists.
