### ISSUE TITLE
Would you consider adding a license?

### ISSUE THREAD

**Issue by JackBurdick** [rdehuyss/micropython-ota-updater#14]
Hi!

I came across this project and it looks really awesome -- any chance you'd consider adding a license?

Thank you!

**Comment by FalconBFR** [comment]
+1

**Comment by rdehuyss** [comment]
It's MIT.

Will add the license when I have some spare time...

**Comment by rdehuyss** [comment]
Resolved with commit 0dc799e10088

**Comment by JackBurdick** [comment]
Thank you!
