### ISSUE TITLE
OSError: -40

### ISSUE THREAD

**Issue by suysh** [rdehuyss/micropython-ota-updater#8]

**Comment by suysh** [comment]
After some trials I managed to get it going.
But now I get an error:
```
Traceback (most recent call last):
  File "main.py", line 24, in <module>
  File "main.py", line 20, in boot
  File "main.py", line 8, in download_and_install_update_if_available
  File "main/ota_updater.py", line 49, in download_and_install_update_if_available
  File "main/ota_updater.py", line 56, in _download_and_install_update
  File "main/ota_updater.py", line 127, in download_all_files
  File "main/ota_updater.py", line 139, in download_file
  File "main/ota_updater.py", line 270, in get
  File "main/ota_updater.py", line 216, in request
OSError: -40
```
A quick search for this error : https://github.com/micropython/micropython-lib/issues/400
Is the script still working on your place?
Kind regards, Hans

**Comment by FalconBFR** [comment]
Hi, just to check, what is your line 216? I am getting an error at line 207 (OS Error 202) and my 207 is 
`ai = usocket.getaddrinfo(host, port, 0, usocket.SOCK_STREAM)`

Thanks!

**Comment by rdehuyss** [comment]
Hi,

I just updated the OTAUpdater to the latest version which I developed over the last months. Can you try that and start a new issue if stuff does not work?

I used it yesterday and it works nicely for me. It is used in the following project: [https://github.com/rdehuyss/chicken-shed-mgr/tree/main/src/app/utils](https://github.com/rdehuyss/chicken-shed-mgr/tree/main/src/app/utils).

> Do note that there I split the httpclient from the OTAUpdater as it is also used to do logging to GitHub gists.

**Comment by FalconBFR** [comment]
> Hi,
> 
> I just updated the OTAUpdater to the latest version which I developed over the last months. Can you try that and start a new issue if stuff does not work?
> 
> I used it yesterday and it works nicely for me. It is used in the following project: https://github.com/rdehuyss/chicken-shed-mgr/tree/main/src/app/utils.
> 
> > Do note that there I split the httpclient from the OTAUpdater as it is also used to do logging to GitHub gists.

Thanks so much! Will check!
